# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nonoho/git/violetta

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nonoho/git/violetta

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nonoho/git/violetta/CMakeFiles /home/nonoho/git/violetta//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nonoho/git/violetta/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named debug_taniho

# Build rule for target.
debug_taniho: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug_taniho
.PHONY : debug_taniho

# fast build rule for target.
debug_taniho/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_taniho.dir/build.make CMakeFiles/debug_taniho.dir/build
.PHONY : debug_taniho/fast

#=============================================================================
# Target rules for targets named mpl

# Build rule for target.
mpl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mpl
.PHONY : mpl

# fast build rule for target.
mpl/fast:
	$(MAKE) $(MAKESILENT) -f Library/mpl/CMakeFiles/mpl.dir/build.make Library/mpl/CMakeFiles/mpl.dir/build
.PHONY : mpl/fast

#=============================================================================
# Target rules for targets named taniho

# Build rule for target.
taniho: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taniho
.PHONY : taniho

# fast build rule for target.
taniho/fast:
	$(MAKE) $(MAKESILENT) -f Project/reko/CMakeFiles/taniho.dir/build.make Project/reko/CMakeFiles/taniho.dir/build
.PHONY : taniho/fast

#=============================================================================
# Target rules for targets named GitHash

# Build rule for target.
GitHash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GitHash
.PHONY : GitHash

# fast build rule for target.
GitHash/fast:
	$(MAKE) $(MAKESILENT) -f Tool/Githash/CMakeFiles/GitHash.dir/build.make Tool/Githash/CMakeFiles/GitHash.dir/build
.PHONY : GitHash/fast

Project/taniho/taniho_linux.o: Project/taniho/taniho_linux.cpp.o
.PHONY : Project/taniho/taniho_linux.o

# target to build an object file
Project/taniho/taniho_linux.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_taniho.dir/build.make CMakeFiles/debug_taniho.dir/Project/taniho/taniho_linux.cpp.o
.PHONY : Project/taniho/taniho_linux.cpp.o

Project/taniho/taniho_linux.i: Project/taniho/taniho_linux.cpp.i
.PHONY : Project/taniho/taniho_linux.i

# target to preprocess a source file
Project/taniho/taniho_linux.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_taniho.dir/build.make CMakeFiles/debug_taniho.dir/Project/taniho/taniho_linux.cpp.i
.PHONY : Project/taniho/taniho_linux.cpp.i

Project/taniho/taniho_linux.s: Project/taniho/taniho_linux.cpp.s
.PHONY : Project/taniho/taniho_linux.s

# target to generate assembly for a file
Project/taniho/taniho_linux.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug_taniho.dir/build.make CMakeFiles/debug_taniho.dir/Project/taniho/taniho_linux.cpp.s
.PHONY : Project/taniho/taniho_linux.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GitHash"
	@echo "... debug_taniho"
	@echo "... mpl"
	@echo "... taniho"
	@echo "... Project/taniho/taniho_linux.o"
	@echo "... Project/taniho/taniho_linux.i"
	@echo "... Project/taniho/taniho_linux.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

